spring:
  profiles:
  - dev

  h2:
    console:
      path: /h2
      settings:
        web-allow-others: true
        
  datasource:
    url: jdbc:h2:mem:greetingDb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true

greetingDateFormat: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"
