spring:
  profiles:
    active: ${greeting.profiles.active}
  application:
    name: initdemo
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      

      